apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: metrics
      port: 9600
      targetPort: 9600
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.9.0
          ports:
            - containerPort: 9200
            - containerPort: 9600
          env:
            - name: discovery.type
              value: "single-node"
            - name: plugins.security.disabled
              value: "true"
            - name: bootstrap.memory_lock
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: opensearch-storage
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-storage
          persistentVolumeClaim:
            claimName: opensearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: dashboards
spec:
  selector:
    app: dashboards
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboards
  template:
    metadata:
      labels:
        app: dashboards
    spec:
      containers:
        - name: dashboards
          image: opensearchproject/opensearch-dashboards:2.9.0
          ports:
            - containerPort: 5601
          env:
            - name: OPENSEARCH_HOSTS
              value: '["http://opensearch:9200"]'
            - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
              value: "true"
