import React from 'react';
import {useCurrentFrame} from 'remotion';
import {C} from '../design/tokens';
import {blocks,cell,cols,entrance,milkRoute,path,Point,products,px,rows} from '../data/store';
import {lerp,linear} from '../utils/motion';

export const Atmosphere:React.FC=()=> <div style={{position:'absolute',inset:0,background:`radial-gradient(ellipse at 72% 42%, #12373b 0%, ${C.bg} 54%, #050b10 100%)`}}><div style={{position:'absolute',inset:0,opacity:.13,backgroundImage:'linear-gradient(#2d5b64 1px, transparent 1px),linear-gradient(90deg,#2d5b64 1px,transparent 1px)',backgroundSize:'80px 80px',maskImage:'linear-gradient(90deg,transparent,#000 35%,#000 80%,transparent)'}}/></div>;
export const Eyebrow:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{fontSize:22,letterSpacing:5,fontWeight:700,color:C.mint,textTransform:'uppercase',...style}}>{children}</div>;
export const Headline:React.FC<{children:React.ReactNode;top?:number;width?:number;size?:number}>=({children,top=330,width=750,size=80})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:130,top,width,fontSize:size,fontWeight:700,letterSpacing:-4,lineHeight:1.08,color:C.white,opacity:lerp(f,10,35),transform:`translateY(${(1-lerp(f,10,35))*34}px)`,textShadow:'0 12px 36px #0008'}}>{children}</div>};
export const Concept:React.FC<{left?:number;top?:number}>=({left=130,top=950})=><div style={{position:'absolute',left,top,color:C.muted,fontSize:20,letterSpacing:1.5}}>KONZEPTDARSTELLUNG</div>;

export const RouteGlyph:React.FC<{size?:number}>=({size=94})=><svg width={size} height={size} viewBox="0 0 100 100"><path d="M20 77 C20 48 47 65 45 36 C44 17 77 15 79 37 C82 56 57 52 59 77" fill="none" stroke={C.mint} strokeWidth="9" strokeLinecap="round"/><circle cx="20" cy="77" r="8" fill={C.mint}/><circle cx="59" cy="77" r="8" fill={C.mint}/></svg>;
export const Wordmark:React.FC<{size?:number;claim?:boolean}>=({size=112,claim=false})=><div style={{display:'flex',alignItems:'center',gap:18}}><RouteGlyph size={size*.88}/><div><div style={{fontSize:size,fontWeight:800,letterSpacing:-6,lineHeight:.95}}>INDOORO</div>{claim&&<div style={{fontSize:42,color:C.muted,letterSpacing:-1,marginTop:24}}>Finde deinen Weg.</div>}</div></div>;

export const MapGraphic:React.FC<{routePoints?:Point[];progress?:number;routeColor?:string;showMarkers?:boolean;showBeacon?:boolean;showGrid?:boolean;showNodes?:boolean;highlight?:string;opacity?:number}>=({routePoints,progress=1,routeColor=C.mint,showMarkers=true,showBeacon=false,showGrid=true,showNodes=false,highlight,opacity=1})=>{
  const f=useCurrentFrame();const len=routePoints?Math.max(1,routePoints.slice(1).reduce((sum,p,i)=>sum+Math.hypot((p.x-routePoints[i].x)*cell,(p.y-routePoints[i].y)*cell),0)):1;
  return <svg viewBox={`0 0 ${cols*cell} ${rows*cell}`} width="100%" height="100%" style={{opacity,filter:'drop-shadow(0 22px 42px #0008)'}}>
    <rect x="0" y="0" width={cols*cell} height={rows*cell} rx="27" fill={C.plane} stroke={C.stroke} strokeWidth="2"/>
    {showGrid&&Array.from({length:cols-1},(_,i)=><line key={`v${i}`} x1={(i+1)*cell} x2={(i+1)*cell} y1="0" y2={rows*cell} stroke="#28464d" strokeOpacity=".27"/>)}
    {showGrid&&Array.from({length:rows-1},(_,i)=><line key={`h${i}`} y1={(i+1)*cell} y2={(i+1)*cell} x1="0" x2={cols*cell} stroke="#28464d" strokeOpacity=".27"/>)}
    {blocks.map((b,i)=><g key={i}><rect x={b.x*cell+5} y={b.y*cell+5} width={b.w*cell-10} height={b.h*cell-10} rx="10" fill={highlight===b.label?'#245F56':C.panel2} stroke={highlight===b.label?C.mint:'#41616a'} strokeWidth={highlight===b.label?3:1.5}/><path d={`M${b.x*cell+17} ${b.y*cell+18} H${(b.x+b.w)*cell-17}`} stroke={highlight===b.label?C.mint:'#507079'} strokeWidth="2"/><text x={(b.x+b.w/2)*cell} y={(b.y+b.h/2)*cell+5} fill={highlight===b.label?C.white:'#8DA8AD'} fontSize="15" textAnchor="middle" fontWeight="700">{b.label}</text></g>)}
    {showNodes&&Array.from({length:cols*rows},(_,i)=>({x:i%cols,y:Math.floor(i/cols)})).filter(p=>!blocks.some(b=>p.x>=b.x&&p.x<b.x+b.w&&p.y>=b.y&&p.y<b.y+b.h)).map((p,i)=><circle key={i} cx={px(p).x} cy={px(p).y} r="2.5" fill={C.teal} opacity={lerp(f,15+(Math.abs(p.x-entrance.x)+Math.abs(p.y-entrance.y))*4,40+(Math.abs(p.x-entrance.x)+Math.abs(p.y-entrance.y))*4,0,.55)}/>)}
    {showBeacon&&[{x:1,y:1},{x:9,y:1},{x:16,y:9}].map((p,i)=><g key={i}><circle cx={px(p).x} cy={px(p).y} r={25+((f+i*19)%75)*1.1} fill="none" stroke={C.teal} strokeWidth="2" opacity={.23*(1-((f+i*19)%75)/75)}/><circle cx={px(p).x} cy={px(p).y} r="7" fill={C.teal}/></g>)}
    {routePoints&&<><path d={path(routePoints)} fill="none" stroke={routeColor} opacity=".15" strokeWidth="23" strokeLinecap="round" strokeLinejoin="round"/><path d={path(routePoints)} fill="none" stroke={routeColor} strokeWidth="8" strokeLinecap="round" strokeLinejoin="round" strokeDasharray={len} strokeDashoffset={len*(1-progress)} style={{filter:`drop-shadow(0 0 7px ${routeColor})`}}/></>}
    {showMarkers&&<><circle cx={px(entrance).x} cy={px(entrance).y} r="16" fill={C.bg} stroke={C.mint} strokeWidth="4"/><circle cx={px(entrance).x} cy={px(entrance).y} r="7" fill={C.mint}/><text x={px(entrance).x+23} y={px(entrance).y+7} fill={C.white} fontSize="17">START</text><circle cx={px(products.Milch).x} cy={px(products.Milch).y} r="16" fill={C.mint} opacity={lerp(f,10,35,.2,1)}/><circle cx={px(products.Milch).x} cy={px(products.Milch).y} r="6" fill={C.bg}/></>}
  </svg>;
};

export const Phone:React.FC<{mode:'home'|'search'|'map'|'list';scale?:number;rotate?:number}>=({mode,scale=1,rotate=-4})=>{
  const f=useCurrentFrame();return <div style={{width:438,height:860,transform:`scale(${scale}) rotate(${rotate}deg)`,transformOrigin:'center',borderRadius:67,background:'linear-gradient(130deg,#668087,#0b151a 22%,#152831 84%,#6a8588)',padding:11,boxShadow:'0 44px 85px #000b,0 0 0 2px #9eb4b355',position:'relative'}}>
    <div style={{width:'100%',height:'100%',borderRadius:57,overflow:'hidden',background:C.bg,border:'2px solid #243d44',position:'relative'}}>
      <div style={{height:56,position:'absolute',top:8,left:'50%',transform:'translateX(-50%)',background:'#020608',borderRadius:30,width:132,zIndex:5}}/>
      <div style={{padding:'87px 30px 25px',height:'100%',background:'radial-gradient(circle at 75% 18%,#173c3e,#0c1b22 58%)'}}>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:35}}><div style={{fontSize:25,fontWeight:800,letterSpacing:-1,color:C.white}}>indooro<span style={{color:C.mint}}>.</span></div><div style={{width:38,height:38,borderRadius:20,background:C.panel2,border:`1px solid ${C.stroke}`}}/></div>
        {mode==='home'&&<><div style={{fontSize:38,fontWeight:750,lineHeight:1.1,marginTop:90}}>Alles finden.<br/><span style={{color:C.mint}}>Einfach ankommen.</span></div><div style={{marginTop:45,background:C.panel2,borderRadius:20,padding:23,color:C.muted,fontSize:22}}>⌕ &nbsp; Produkt suchen</div><div style={{marginTop:37,height:330}}><MapGraphic routePoints={undefined} showMarkers={false}/></div></>}
        {mode==='search'&&<><div style={{fontSize:31,fontWeight:700}}>Was suchst du?</div><div style={{marginTop:28,background:C.panel2,border:`2px solid ${C.mint}`,borderRadius:18,padding:'20px 22px',fontSize:25,minHeight:73}}>⌕ &nbsp; {`Milch`.slice(0,Math.round(linear(f,35,92,0,5)))}</div><div style={{marginTop:25,fontSize:19,color:C.muted}}>PRODUKTE</div><div style={{opacity:lerp(f,95,118),marginTop:16,background:C.panel,borderRadius:20,padding:22,border:'1px solid #31515A',display:'flex',justifyContent:'space-between',fontSize:23}}><span>🥛 &nbsp; Milch</span><span style={{color:C.mint}}>›</span></div><div style={{opacity:lerp(f,125,150),marginTop:15,color:C.muted,fontSize:19}}>Kühlregal · Gang 4</div></>}
        {mode==='map'&&<><div style={{fontSize:28,fontWeight:700,marginBottom:20}}>Route zu Milch</div><div style={{height:495,background:C.panel,borderRadius:21,overflow:'hidden',padding:8}}><MapGraphic routePoints={milkRoute} highlight="Milch"/></div><div style={{marginTop:22,background:C.mint,borderRadius:17,padding:20,color:C.bg,fontSize:22,fontWeight:800,textAlign:'center'}}>Route anzeigen &nbsp; ↗</div></>}
        {mode==='list'&&<><div style={{fontSize:32,fontWeight:700,marginBottom:20}}>Meine Liste</div>{['Milch','Brot','Nudeln','Äpfel'].map((s,i)=><div key={s} style={{background:C.panel,borderRadius:16,padding:19,marginBottom:13,fontSize:23,opacity:lerp(f,i*9,i*9+15)}}><span style={{color:C.mint,marginRight:14}}>◯</span>{s}</div>)}<div style={{marginTop:20,height:300}}><MapGraphic routePoints={undefined} showMarkers={false}/></div></>}
      </div>
      <div style={{position:'absolute',inset:0,pointerEvents:'none',background:'linear-gradient(115deg,#ffffff12 0%,transparent 21%,transparent 72%,#ffffff07 96%)'}}/>
    </div>
  </div>;
};
