import React from 'react';
import {AbsoluteFill,useCurrentFrame} from 'remotion';
import {C} from '../design/tokens';
import {entrance,inefficient,milkRoute,names,optimized,products,px,tourPath} from '../data/store';
import {Headline,Eyebrow,MapGraphic,Phone,Wordmark,Concept,RouteGlyph} from '../components/Visuals';
import {lerp,linear} from '../utils/motion';

const MapStage:React.FC<{children:React.ReactNode;left?:number;top?:number;width?:number;rotate?:number;scale?:number;opacity?:number}>=({children,left=875,top=250,width=900,rotate=0,scale=1,opacity=1})=><div style={{position:'absolute',left,top,width,height:width*11/18,transform:`rotate(${rotate}deg) scale(${scale})`,transformOrigin:'center',opacity}}>{children}</div>;
const Section:React.FC<{children:React.ReactNode;number:string;label:string}>=({children,number,label})=><AbsoluteFill><div style={{position:'absolute',left:130,top:106,display:'flex',gap:18,alignItems:'center'}}><span style={{color:C.mint,fontSize:22,fontWeight:800}}>{number}</span><span style={{width:56,height:1,background:C.stroke}}/><Eyebrow>{label}</Eyebrow></div>{children}</AbsoluteFill>;

export const Problem:React.FC=()=>{const f=useCurrentFrame();const wander=[entrance,{x:1,y:7},{x:2,y:7},{x:2,y:5},{x:6,y:5},{x:6,y:6},{x:10,y:6},{x:10,y:5},{x:14,y:5},{x:14,y:3}];return <Section number="01" label="DIE FRAGE"><Headline top={362} width={670} size={80}>Wo ist eigentlich<br/><span style={{color:C.mint}}>die Milch?</span></Headline><MapStage left={805} top={300} width={970} rotate={lerp(f,0,160,8,3)} scale={lerp(f,0,160,1.07,1)}><MapGraphic routePoints={wander} progress={linear(f,35,150)} routeColor={C.amber} showMarkers={false}/></MapStage><div style={{position:'absolute',left:130,top:655,fontSize:29,color:C.muted,opacity:lerp(f,55,88)}}>Ein Produkt. Viele Wege.</div><div style={{position:'absolute',left:1000,top:780,width:250,height:250,borderRadius:200,background:C.mint,filter:'blur(130px)',opacity:.08}}/></Section>};

export const Reveal:React.FC=()=>{const f=useCurrentFrame();return <Section number="02" label="DIE IDEE"><div style={{position:'absolute',left:130,top:375,opacity:lerp(f,20,50),transform:`translateY(${(1-lerp(f,20,50))*30}px)`}}><Wordmark size={105}/><div style={{fontSize:38,color:C.muted,marginTop:45}}>Dein Weg durch den Supermarkt.</div></div><div style={{position:'absolute',left:1140,top:110,opacity:lerp(f,0,35),transform:`translateY(${(1-lerp(f,0,60))*80}px) scale(${lerp(f,0,175,.82,1.02)}) rotate(${lerp(f,0,175,-4,0)}deg)`}}><Phone mode="home" scale={.88} rotate={-4}/></div><div style={{position:'absolute',left:1110,top:250,width:420,height:650,borderRadius:'50%',background:C.mint,opacity:.10,filter:'blur(100px)'}}/></Section>};

export const Search:React.FC=()=>{const f=useCurrentFrame();return <Section number="03" label="PRODUKT FINDEN"><Headline top={420} width={650} size={78}>Finden statt<br/><span style={{color:C.mint}}>suchen.</span></Headline><div style={{position:'absolute',left:1130,top:90,transform:`scale(${lerp(f,0,300,.94,1)})`,transformOrigin:'top left'}}><Phone mode={f<180?'search':'map'} scale={.95} rotate={lerp(f,0,260,-3,0)}/></div><Concept left={1190} top={1000}/><div style={{position:'absolute',left:130,top:660,color:C.muted,fontSize:28,opacity:lerp(f,80,120)}}>Suche → Produkt → Regal</div></Section>};

export const Position:React.FC=()=>{const f=useCurrentFrame();const at=milkRoute[Math.min(milkRoute.length-1,Math.floor(linear(f,95,255,0,milkRoute.length-1)))];const p=px(at);return <Section number="04" label="ORIENTIERUNG"><Headline top={370} width={610} size={76}>Navigation.<br/><span style={{color:C.mint}}>Auch indoor.</span></Headline><MapStage left={760} top={245} width={1050} rotate={lerp(f,0,170,5,0)} scale={lerp(f,0,170,1.08,1)}><MapGraphic routePoints={milkRoute} progress={linear(f,145,245)} showBeacon showMarkers={false}/><div style={{position:'absolute',left:`${p.x/864*100}%`,top:`${p.y/528*100}%`,width:25,height:25,borderRadius:20,background:C.mint,boxShadow:`0 0 0 10px #63e6b444,0 0 30px ${C.mint}`,transform:'translate(-50%,-50%)'}}/></MapStage><div style={{position:'absolute',left:130,top:660,display:'flex',gap:18,opacity:lerp(f,40,80)}}>{['BLE','MAP MATCHING','A*'].map(s=><div key={s} style={{border:`1px solid ${C.stroke}`,borderRadius:30,padding:'12px 20px',fontSize:20,color:C.muted,letterSpacing:1}}>{s}</div>)}</div><Concept left={130} top={950}/></Section>};

export const Route:React.FC=()=>{const f=useCurrentFrame();return <Section number="05" label="DER WEG"><Headline top={380} width={620} size={77}>Der passende<br/><span style={{color:C.mint}}>Weg.</span></Headline><div style={{position:'absolute',left:130,top:635,fontSize:24,letterSpacing:2,color:C.muted,opacity:lerp(f,20,45)}}>A* · WEGFINDUNG</div><MapStage left={760} top={255} width={1070} scale={lerp(f,0,270,1,1.04)}><MapGraphic routePoints={milkRoute} progress={linear(f,95,205)} showNodes showMarkers/></MapStage><div style={{position:'absolute',left:950,top:890,color:C.muted,fontSize:21,opacity:lerp(f,80,120)}}>Nur begehbare Wege verbinden Start und Ziel.</div></Section>};

export const List:React.FC=()=>{
  const f=useCurrentFrame(),oldOpacity=1-lerp(f,105,120),newOpacity=lerp(f,130,150),arrival=lerp(f,10,35);
  const rows=(order:typeof inefficient,opacity:number,offset:number)=>order.map((name,i)=><div key={name} style={{position:'absolute',left:24+offset,top:65+i*62,width:430,height:62,display:'flex',alignItems:'center',gap:16,borderBottom:'1px solid #31515A',fontSize:27,opacity:opacity*lerp(f,15+i*9,35+i*9)}}><span style={{color:order===optimized?C.mint:C.amber,fontSize:18}}>0{i+1}</span>{name}</div>);
  const pins=(color:string)=>names.map(name=><div key={name} style={{position:'absolute',left:`${px(products[name]).x/864*100}%`,top:`${px(products[name]).y/528*100}%`,width:24,height:24,borderRadius:14,background:color,transform:'translate(-50%,-50%)',border:`4px solid ${C.bg}`}}/>);
  return <Section number="06" label="EINKAUF PLANEN">
    <div style={{position:'absolute',left:130,top:280,width:670,fontSize:72,fontWeight:700,letterSpacing:-4,lineHeight:1.08,opacity:arrival*oldOpacity}}>Eine <span style={{color:C.mint}}>Liste.</span></div>
    <div style={{position:'absolute',left:130,top:280,width:670,fontSize:72,fontWeight:700,letterSpacing:-4,lineHeight:1.08,opacity:newOpacity}}>Ein durchdachter<br/><span style={{color:C.mint}}>Weg.</span></div>
    <div style={{position:'absolute',left:130,top:560,width:480,height:337,background:C.panel,border:`1px solid ${C.stroke}`,borderRadius:27,padding:24,boxShadow:'0 24px 60px #0007'}}>
      <div style={{fontSize:22,color:C.muted,marginBottom:12}}>MEIN EINKAUF</div>
      {rows(inefficient,oldOpacity,-20*(1-oldOpacity))}
      {rows(optimized,newOpacity,20*(1-newOpacity))}
    </div>
    <MapStage left={755} top={255} width={1080} rotate={lerp(f,0,210,4,0)}>
      <MapGraphic showMarkers={false}/>
      <div style={{position:'absolute',inset:0,opacity:oldOpacity}}><MapGraphic routePoints={tourPath(inefficient)} progress={linear(f,35,105)} routeColor={C.amber} showMarkers={false}/>{pins(C.amber)}</div>
      <div style={{position:'absolute',inset:0,opacity:newOpacity}}><MapGraphic routePoints={tourPath(optimized)} progress={linear(f,130,210)} routeColor={C.mint} showMarkers={false}/>{pins(C.mint)}</div>
    </MapStage>
    <div style={{position:'absolute',left:130,top:935,color:C.muted,fontSize:20,letterSpacing:1.4}}>LOKALE TOUR · ILLUSTRATIVES BEISPIEL</div>
  </Section>;
};

export const Admin:React.FC=()=>{const f=useCurrentFrame();return <Section number="07" label="HINTER DEM WEG"><Headline top={375} width={580} size={76}>Flexibel<br/><span style={{color:C.mint}}>verwalten.</span></Headline><div style={{position:'absolute',left:780,top:198,width:1050,height:675,borderRadius:28,background:C.panel,boxShadow:'0 35px 85px #0009',border:`1px solid ${C.stroke}`,overflow:'hidden',transform:`scale(${lerp(f,0,200,1.05,1)})`}}><div style={{height:67,borderBottom:`1px solid ${C.stroke}`,display:'flex',alignItems:'center',padding:'0 28px',justifyContent:'space-between'}}><span style={{fontSize:24,fontWeight:800}}>indooro<span style={{color:C.mint}}>.</span> <span style={{color:C.muted,fontWeight:400}}> / Layout Editor</span></span><span style={{padding:'9px 18px',background:C.mint,color:C.bg,borderRadius:10,fontSize:20,fontWeight:700}}>✓ Gespeichert</span></div><div style={{display:'flex',height:608}}><div style={{width:175,padding:20,borderRight:`1px solid ${C.stroke}`,color:C.muted,fontSize:21,lineHeight:2.4}}>Übersicht<br/><span style={{color:C.mint}}>Layout</span><br/>Produkte<br/>Beacons</div><div style={{width:640,padding:25}}><MapGraphic showMarkers={false} highlight={f>70?'Milch':undefined}/></div><div style={{flex:1,borderLeft:`1px solid ${C.stroke}`,padding:22}}><div style={{fontSize:20,color:C.muted}}>AUSWAHL</div><div style={{fontSize:28,fontWeight:700,marginTop:20}}>Kühlregal</div><div style={{fontSize:19,color:C.muted,marginTop:24}}>Produktposition</div><div style={{fontSize:23,color:C.mint,marginTop:10,opacity:lerp(f,80,115)}}>Milch ↗</div><div style={{marginTop:80,height:1,background:C.stroke}}/><div style={{fontSize:18,color:C.muted,marginTop:25}}>Gang 4 · Regal 1</div></div></div></div><Concept left={1320} top={910}/></Section>};

export const Hero:React.FC=()=>{const f=useCurrentFrame();return <Section number="08" label="INDOORO"><div style={{position:'absolute',left:130,top:392,opacity:lerp(f,22,62),transform:`translateY(${(1-lerp(f,22,62))*30}px)`}}><Wordmark size={108} claim/></div><div style={{position:'absolute',left:1100,top:90,opacity:.75,transform:`scale(${lerp(f,0,90,.86,.94)})`,transformOrigin:'top left'}}><Phone mode="map" rotate={-4}/></div><div style={{position:'absolute',left:945,top:360,width:650,height:350,background:C.mint,filter:'blur(150px)',opacity:.09}}/><div style={{position:'absolute',left:135,top:880,fontSize:22,color:C.muted,opacity:lerp(f,70,95)}}>HTL LEONDING · PROJEKT</div><Concept left={1500} top={1008}/></Section>};

export const Poster:React.FC=()=> <AbsoluteFill style={{background:C.bg}}><div style={{position:'absolute',left:130,top:400}}><Wordmark size={108} claim/></div><div style={{position:'absolute',left:1100,top:90}}><Phone mode="map" rotate={-4}/></div><div style={{position:'absolute',left:130,top:880,fontSize:22,color:C.muted}}>HTL LEONDING · PROJEKT</div><div style={{position:'absolute',left:130,top:106}}><RouteGlyph size={38}/></div><Concept left={1500} top={1008}/></AbsoluteFill>;
