"""Deterministic Indooro V2 draft 3D passes. Blender 5.2+.
Usage: blender -b --factory-startup --python render_prototype.py -- P1|P3|P4 [still_frame]
Output: public/3d-passes/<prototype>/frame_0001.png ...
No final film is generated by this script.
"""
import bpy, json, math, sys
from pathlib import Path
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view

ROOT = Path(__file__).resolve().parents[2]
LAYOUT = json.loads((ROOT / "src/data/store-layout.json").read_text())
ARGS = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
KIND = ARGS[0] if ARGS else "P1"
STILL = int(ARGS[1]) if len(ARGS) > 1 else None
if KIND not in {"P1", "P3", "P4"}:
    raise ValueError("Expected P1, P3, or P4")

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)
scene = bpy.context.scene
scene.render.engine = "BLENDER_EEVEE"
scene.render.resolution_x = 1280
scene.render.resolution_y = 720
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = "PNG"
scene.render.image_settings.color_mode = "RGB"
scene.render.film_transparent = False
scene.render.fps = 30
scene.frame_start, scene.frame_end = 1, 120
scene.render.filepath = str(ROOT / "public/3d-passes" / KIND / "frame_")
scene.render.image_settings.color_depth = "8"
scene.view_settings.view_transform = "AgX"
scene.view_settings.look = "AgX - Medium High Contrast"
scene.render.film_transparent = False
try:
    scene.eevee.taa_render_samples = 24
except AttributeError:
    pass
scene.world.color = (0.012, 0.02, 0.025)
outdir = ROOT / "public/3d-passes" / KIND
outdir.mkdir(parents=True, exist_ok=True)

def material(name, color, rough=.65, metallic=0, emission=None, strength=0):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*color, 1)
    mat.use_nodes = True
    p = mat.node_tree.nodes.get("Principled BSDF")
    p.inputs["Base Color"].default_value = (*color, 1)
    p.inputs["Roughness"].default_value = rough
    p.inputs["Metallic"].default_value = metallic
    if emission is not None:
        p.inputs["Emission Color"].default_value = (*emission, 1)
        p.inputs["Emission Strength"].default_value = strength
    return mat

FLOOR = material("graphite floor", (.018,.033,.042), .78, .16)
SHELF = material("matte shelf graphite", (.038,.068,.075), .7, .2)
SHELF_FACE = material("shelf edge", (.075,.12,.13), .55, .35)
PRODUCT = material("abstract product backs", (.085,.13,.14), .8, .02)
MINT = material("Indooro mint route", (.05,.55,.36), .3, .06, (.04,.57,.36), .75)
SOFT_MINT = material("soft mint", (.11,.28,.25), .65, .05, (.14,.65,.48), .4)
AMBER = material("uncertainty amber", (.64,.39,.16), .7, 0, (.55,.28,.08), .4)
COAT = material("shopper graphite ceramic fabric", (.045,.057,.061), .9, .01)
COAT_EDGE = material("shopper seams", (.032,.043,.047), .91, .0)
HEAD = material("shopper matte head", (.061,.075,.078), .87, .01)
MILK = material("generic milk carton", (.78,.81,.76), .62, 0)
MILK_TOP = material("carton folded top", (.65,.70,.67), .7, 0)

def box(name, loc, size, mat, bevel=0):
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    ob = bpy.context.object
    ob.name = name
    ob.dimensions = size
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    ob.data.materials.append(mat)
    if bevel:
        mod = ob.modifiers.new("soft bevel", "BEVEL")
        mod.width = bevel
        mod.segments = 2
        ob.modifiers.new("weighted normals", "WEIGHTED_NORMAL")
    return ob

def sphere(name, loc, scale, mat):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=20, ring_count=12, location=loc)
    ob=bpy.context.object; ob.name=name
    ob.scale=scale
    ob.data.materials.append(mat)
    for poly in ob.data.polygons: poly.use_smooth=True
    return ob

def tapered(name, loc, radius_lower, radius_upper, depth, mat, bevel=.025):
    bpy.ops.mesh.primitive_cone_add(vertices=20, radius1=radius_lower, radius2=radius_upper, depth=depth, location=loc)
    ob=bpy.context.object;ob.name=name;ob.data.materials.append(mat)
    mod=ob.modifiers.new("soft clothing edge","BEVEL");mod.width=bevel;mod.segments=2
    ob.modifiers.new("weighted normals","WEIGHTED_NORMAL")
    return ob

def curve_line(name, coords, radius, mat):
    curve=bpy.data.curves.new(name,"CURVE"); curve.dimensions="3D"; curve.resolution_u=12
    curve.bevel_depth=radius; curve.bevel_resolution=3
    spline=curve.splines.new("POLY"); spline.points.add(len(coords)-1)
    for p,co in zip(spline.points,coords): p.co=(*co,1)
    ob=bpy.data.objects.new(name,curve); bpy.context.collection.objects.link(ob)
    ob.data.materials.append(mat)
    return ob

def area(name, loc, energy, color, size, target):
    data=bpy.data.lights.new(name,"AREA"); data.energy=energy; data.color=color; data.shape="DISK"; data.size=size
    ob=bpy.data.objects.new(name,data); bpy.context.collection.objects.link(ob); ob.location=loc
    direction=Vector(target)-ob.location; ob.rotation_euler=direction.to_track_quat("-Z","Y").to_euler()
    return ob

def look(cam, target):
    direction=Vector(target)-cam.location
    cam.rotation_euler=direction.to_track_quat("-Z","Y").to_euler()

def cam_key(cam, frame, loc, target, lens=35):
    cam.location=loc; look(cam,target); cam.data.lens=lens
    cam.keyframe_insert(data_path="location",frame=frame)
    cam.keyframe_insert(data_path="rotation_euler",frame=frame)
    cam.data.keyframe_insert(data_path="lens",frame=frame)

# Floor and a sparse architectural kit.
box("floor", (0,0,-.095), (18,19,.17), FLOOR, .04)
for s in LAYOUT["shelves"]:
    x,y=s["x"],s["y"]; w,l,h=s["width"],s["length"],s["height"]
    body=box(s["id"]+" monolith", (x,y,h/2), (w,l,h), SHELF, .045)
    if KIND=="P3":
        body.scale.z=.012; body.keyframe_insert(data_path="scale",frame=1)
        body.scale.z=.012; body.keyframe_insert(data_path="scale",frame=42)
        body.scale.z=1; body.keyframe_insert(data_path="scale",frame=83)
    for level in (0.5,1.05,1.6,2.16):
        for side in (-1,1):
            strip=box(s["id"]+" shelf rail", (x+side*(w/2+.015),y,level),(.035,l-.18,.045),SHELF_FACE,.01)
            if KIND=="P3":
                strip.hide_render=True
        if KIND!="P3":
            for yi in range(6):
                yy=y-l/2+.55+yi*(l-.9)/5
                for side in (-1,1):
                    box(s["id"]+" abstract stock", (x+side*(w/2+.045),yy,level+.16),
                        (.08,.22,.24),PRODUCT,.015)
    for end in (-1,1):
        box(s["id"]+" end cap",(x,y+end*(l/2-.05),h/2),(.055,.08,h-.15),SHELF_FACE,.01)
# Cool floor joints, a few intentional ceiling light lines.
for x in (-5.25,-2.75,0,3,5.25):
    curve_line("quiet floor joint",[(x,-6,.008),(x,5.8,.008)],.005,SHELF_FACE)
for x in (-3.0,3.0):
    box("ceiling light housing",(x,-.8,3.55),(.06,8,.025),SHELF_FACE,.01)
    box("ceiling cool strip",(x,-.8,3.52),(.025,7.8,.011),SOFT_MINT,.003)

def shopper(x,y,angle=0):
    root=bpy.data.objects.new("shopper root",None); bpy.context.collection.objects.link(root)
    root.location=(x,y,0); root.rotation_euler.z=angle
    def child(ob):
        # Prototype poses use world-space geometry. Parenting world-positioned
        # primitives here would double-transform them and break the silhouette.
        return ob
    # One continuous lofted coat mass, not stacked mannequin primitives.
    rings=[(.77,.33,.22),(1.03,.32,.20),(1.44,.39,.20),(1.63,.25,.16)]
    n=16; verts=[]; faces=[]
    for z,rx,ry in rings:
        verts.extend((x+math.cos(2*math.pi*i/n)*rx,y+math.sin(2*math.pi*i/n)*ry,z) for i in range(n))
    for j in range(len(rings)-1):
        for i in range(n): faces.append((j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i))
    faces.extend([tuple(reversed(range(n))),tuple((len(rings)-1)*n+i for i in range(n))])
    mesh=bpy.data.meshes.new("sculpted coat mesh");mesh.from_pydata(verts,[],faces);mesh.update()
    coat=bpy.data.objects.new("continuous sculptural coat",mesh);bpy.context.collection.objects.link(coat)
    coat.data.materials.append(COAT)
    bevel=coat.modifiers.new("seamless coat bevel","BEVEL");bevel.width=.045;bevel.segments=2
    coat.modifiers.new("weighted coat normals","WEIGHTED_NORMAL")
    child(coat)
    child(box("low contrast collar",(x,y,1.61),(.36,.27,.07),COAT_EDGE,.025))
    child(sphere("faceless sculptural head",(x,y,1.83),(.16,.15,.22),HEAD))
    for sign in (-1,1):
        sleeve=child(tapered("soft tapered sleeve",(x+sign*.34,y,1.22),.078,.115,.63,COAT))
        sleeve.scale.y=.82
        child(tapered("trouser",(x+sign*.17,y,0.45),.095,.13,.72,COAT_EDGE))
        child(box("shoe",(x+sign*.17,y-.08,.075),(.20,.34,.14),COAT,.035))
    return root

# Shared route, visually grounded and walkable.
routepts=[(p["x"],p["y"],.035) for p in LAYOUT["route"]]
if KIND in ("P3","P4"):
    path=curve_line("same path in world",routepts,.029,MINT)
    path.data.bevel_factor_end=0.0 if KIND=="P3" else .86
    path.data.keyframe_insert(data_path="bevel_factor_end",frame=1)
    path.data.bevel_factor_end=1
    path.data.keyframe_insert(data_path="bevel_factor_end",frame=85 if KIND=="P3" else 60)

if KIND=="P1":
    person=shopper(-5.1,-5.2,math.radians(-8))
    ph=box("held phone",(-4.70,-5.39,1.14),(.20,.045,.38),SHELF_FACE,.035)
    ph.keyframe_insert(data_path="location",frame=70)
    ph.location.z=1.55; ph.location.x=-4.62; ph.keyframe_insert(data_path="location",frame=98)
    # Controlled light hierarchy; geometry stays fixed.
    key=area("shopper reveal key",(-5,-4,6),650,(.44,.72,.69),5,(-5,-5,1))
    key.data.energy=400;key.data.keyframe_insert(data_path="energy",frame=74)
    key.data.energy=1000;key.data.keyframe_insert(data_path="energy",frame=105)
    area("aisle streak",(2,-2,5),600,(.43,.72,.76),7,(0,0,0))
    camd=bpy.data.cameras.new("cinema camera"); cam=bpy.data.objects.new("cinema camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(0,-6.4,.65),(0,-1.7,1.3),29)
    cam_key(cam,34,(0,-2.1,.7),(0,2.4,1.4),29)
    cam_key(cam,58,(2.7,-1.8,1.05),(2.8,3.6,1.1),30)
    cam_key(cam,75,(-1.8,-7.2,7.0),(-4.55,-4.4,1.1),34)
    cam_key(cam,120,(-2.6,-7.5,6.5),(-4.85,-4.8,1.2),43)
elif KIND=="P3":
    # The top-down footprints rise continuously into store architecture as the camera descends.
    area("overhead key",(0,0,12),1150,(.46,.78,.72),12,(0,0,0))
    area("side mint",(6,1,5),600,(.31,.76,.61),8,(1,0,0))
    camd=bpy.data.cameras.new("map entry camera");cam=bpy.data.objects.new("map entry camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(0,-2,14),(0,-1,0),27)
    cam_key(cam,35,(0,-2,10),(0,-1,0),28)
    cam_key(cam,56,(0,-3,7),(0,-1,0),30)
    cam_key(cam,85,(0,-4.8,3.4),(0,1,1),31)
    cam_key(cam,120,(0,-3.8,1.35),(0,3,1.05),35)
    person=shopper(0,4.5,math.radians(15))
else:
    person=shopper(5.3,2.1,math.radians(90))
    # Warm generic milk carton mounted on target shelf face.
    box("milk carton",(4.52,2.7,1.38),(.20,.34,.49),MILK,.018)
    roof_verts=[(4.42,2.53,1.625),(4.62,2.53,1.625),(4.62,2.87,1.625),(4.42,2.87,1.625),
                (4.52,2.53,1.79),(4.52,2.87,1.79)]
    roof_faces=[(0,1,4),(3,5,2),(0,4,5,3),(1,2,5,4),(0,3,2,1)]
    roof_mesh=bpy.data.meshes.new("folded carton roof mesh")
    roof_mesh.from_pydata(roof_verts,[],roof_faces);roof_mesh.update()
    roof=bpy.data.objects.new("folded milk carton roof",roof_mesh)
    bpy.context.collection.objects.link(roof);roof.data.materials.append(MILK_TOP)
    box("milk mint label",(4.635,2.7,1.36),(.007,.24,.17),SOFT_MINT,.002)
    # The forearm grows from the shoulder along the reach vector so it stays
    # connected to the coat instead of becoming a floating capsule.
    arm=box("reaching arm",(5.18,2.13,1.25),(.28,.17,.15),COAT,.06)
    arm.rotation_euler.z=-.70
    arm.keyframe_insert(data_path="location",frame=74)
    arm.keyframe_insert(data_path="scale",frame=74)
    arm.location=(4.98,2.39,1.39)
    arm.scale.x=3.05
    arm.keyframe_insert(data_path="location",frame=114)
    arm.keyframe_insert(data_path="scale",frame=114)
    area("destination milk key",(4.9,2.5,4.6),550,(.72,.96,.83),3,(4.3,2.7,1.2))
    area("shopper rim",(6,0,3),300,(.30,.70,.64),4,(5,2,1))
    camd=bpy.data.cameras.new("arrival camera");cam=bpy.data.objects.new("arrival camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(5.0,-5.6,.64),(5.0,-1.0,.48),32)
    cam_key(cam,45,(5.08,-1.6,.85),(5.0,2.3,.8),34)
    cam_key(cam,80,(7.8,4.3,3.1),(4.55,2.7,.7),32)
    cam_key(cam,120,(7.55,4.0,2.9),(4.55,2.7,.72),35)

# A deep background, restrained ambient light and contact shadows.
world=bpy.data.worlds.new("dark ambient")
scene.world=world;world.use_nodes=True
world.node_tree.nodes["Background"].inputs["Color"].default_value=(.018,.036,.044,1)
world.node_tree.nodes["Background"].inputs["Strength"].default_value=.38
area("broad ceiling",(0,0,9),900,(.65,.83,.88),12,(0,0,0))
scene.camera.data.clip_end=200
scene.render.engine="BLENDER_EEVEE"
scene.render.filepath=str(outdir/"frame_")
tracked={
    "P1":{"shopper":(-5.1,-5.2,1.4),"phone":(-4.62,-5.39,1.55)},
    "P3":{"routeStart":(-5.1,-5.2,.04),"routeCenter":(0,-1,.04)},
    "P4":{"destination":(5.05,2.7,.04),"milk":(4.52,2.7,1.38)}
}[KIND]
projection=[]
for f in range(1,121):
    scene.frame_set(f)
    projection.append({name:dict(x=round((q:=world_to_camera_view(scene,scene.camera,Vector(point))).x*1280,2),
                                 y=round((1-q.y)*720,2),visible=q.z>0)
                       for name,point in tracked.items()})
(ROOT/"src/data"/f"projection-{KIND}.json").write_text(json.dumps(projection,separators=(",",":")))
if STILL is None:
    bpy.ops.render.render(animation=True)
else:
    if not 1<=STILL<=120: raise ValueError("still_frame must be 1..120")
    scene.frame_set(STILL)
    scene.render.filepath=str(outdir/f"still_{STILL:04d}.png")
    bpy.ops.render.render(write_still=True)
