"""Deterministic Indooro V2 draft 3D passes. Blender 5.2+.
Usage: blender -b --factory-startup --python render_prototype.py -- P1|P3|P4|P5|P6|P7 [still_frame]
Output: public/3d-passes/<prototype>/frame_0001.png ...
No final film is generated by this script.
"""
import bpy, json, math, sys
from pathlib import Path
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view

ROOT = Path(__file__).resolve().parents[2]
LAYOUT = json.loads((ROOT / "src/data/store-layout.json").read_text())
ARGS = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
KIND = ARGS[0] if ARGS else "P1"
STILL = int(ARGS[1]) if len(ARGS) > 1 else None
FRAME_COUNTS = {"P1": 120, "P3": 120, "P4": 120, "P5": 75, "P6": 75, "P7": 90}
if KIND not in FRAME_COUNTS:
    raise ValueError("Expected one of " + ", ".join(FRAME_COUNTS))
FRAME_COUNT = FRAME_COUNTS[KIND]

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)
scene = bpy.context.scene
scene.render.engine = "BLENDER_EEVEE"
scene.render.resolution_x = 1280
scene.render.resolution_y = 720
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = "PNG"
scene.render.image_settings.color_mode = "RGB"
scene.render.film_transparent = False
scene.render.fps = 30
scene.frame_start, scene.frame_end = 1, FRAME_COUNT
scene.render.filepath = str(ROOT / "public/3d-passes" / KIND / "frame_")
scene.render.image_settings.color_depth = "8"
scene.view_settings.view_transform = "AgX"
scene.view_settings.look = "AgX - Medium High Contrast"
scene.render.film_transparent = False
try:
    scene.eevee.taa_render_samples = 24
except AttributeError:
    pass
scene.world.color = (0.012, 0.02, 0.025)
outdir = ROOT / "public/3d-passes" / KIND
outdir.mkdir(parents=True, exist_ok=True)

def material(name, color, rough=.65, metallic=0, emission=None, strength=0):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*color, 1)
    mat.use_nodes = True
    p = mat.node_tree.nodes.get("Principled BSDF")
    p.inputs["Base Color"].default_value = (*color, 1)
    p.inputs["Roughness"].default_value = rough
    p.inputs["Metallic"].default_value = metallic
    if emission is not None:
        p.inputs["Emission Color"].default_value = (*emission, 1)
        p.inputs["Emission Strength"].default_value = strength
    return mat

def micro_surface(mat, scale, bump_strength, bump_distance, rough_min, rough_max,
                  color_min=None, color_max=None):
    """Subtle deterministic procedural surface; no sampled bitmap assets."""
    nodes=mat.node_tree.nodes; links=mat.node_tree.links
    bsdf=nodes.get("Principled BSDF")
    tex=nodes.new("ShaderNodeTexNoise");tex.inputs["Scale"].default_value=scale
    tex.inputs["Detail"].default_value=3
    tex.inputs["Roughness"].default_value=.62
    bump=nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value=bump_strength
    bump.inputs["Distance"].default_value=bump_distance
    links.new(tex.outputs["Fac"],bump.inputs["Height"])
    links.new(bump.outputs["Normal"],bsdf.inputs["Normal"])
    rough=nodes.new("ShaderNodeMapRange")
    rough.inputs["From Min"].default_value=0
    rough.inputs["From Max"].default_value=1
    rough.inputs["To Min"].default_value=rough_min
    rough.inputs["To Max"].default_value=rough_max
    links.new(tex.outputs["Fac"],rough.inputs["Value"])
    links.new(rough.outputs["Result"],bsdf.inputs["Roughness"])
    if color_min is not None and color_max is not None:
        ramp=nodes.new("ShaderNodeValToRGB")
        ramp.color_ramp.elements[0].color=(*color_min,1)
        ramp.color_ramp.elements[1].color=(*color_max,1)
        links.new(tex.outputs["Fac"],ramp.inputs["Fac"])
        links.new(ramp.outputs["Color"],bsdf.inputs["Base Color"])

FLOOR = material("graphite floor", (.022,.037,.047), .78, .16)
SHELF = material("matte shelf graphite", (.045,.073,.081), .7, .2)
SHELF_FACE = material("brushed shelf edge", (.086,.13,.14), .55, .35)
PRODUCT = material("abstract product backs", (.09,.14,.15), .8, .02)
STOCK_A = material("muted paper packages", (.21,.28,.27), .8, .01)
STOCK_B = material("graphite packaged goods", (.11,.17,.18), .75, .04)
STOCK_C = material("warm neutral packages", (.29,.29,.25), .82, .01)
MINT = material("Indooro mint route", (.05,.55,.36), .3, .06, (.04,.57,.36), .75)
SOFT_MINT = material("soft mint", (.11,.28,.25), .65, .05, (.14,.65,.48), .4)
AMBER = material("uncertainty amber", (.64,.39,.16), .7, 0, (.55,.28,.08), .4)
COAT = material("woven graphite coat", (.06,.072,.077), .87, .01)
COAT_EDGE = material("dark coat binding", (.035,.046,.05), .91, .0)
COAT_THREAD = material("fine coat seam", (.13,.15,.15), .83, .0)
HEAD = material("matte ceramic faceless head", (.079,.095,.099), .87, .01)
MILK = material("uncoated milk carton paper", (.78,.81,.76), .62, 0)
MILK_TOP = material("carton folded top", (.65,.70,.67), .7, 0)
INK = material("milk carton printed ink", (.025,.19,.16), .72, 0)
micro_surface(FLOOR,115,.025,.004,.72,.84)
micro_surface(SHELF,90,.025,.003,.54,.71,(.038,.066,.073),(.052,.079,.086))
micro_surface(SHELF_FACE,160,.02,.003,.42,.59)
micro_surface(COAT,75,.055,.005,.76,.94,(.048,.058,.063),(.074,.083,.087))
micro_surface(COAT_EDGE,75,.04,.004,.82,.96)
micro_surface(HEAD,75,.02,.003,.76,.9)
micro_surface(MILK,105,.03,.002,.54,.7,(.73,.77,.73),(.84,.86,.81))

def box(name, loc, size, mat, bevel=0):
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    ob = bpy.context.object
    ob.name = name
    ob.dimensions = size
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    ob.data.materials.append(mat)
    if bevel:
        mod = ob.modifiers.new("soft bevel", "BEVEL")
        mod.width = bevel
        mod.segments = 2
        ob.modifiers.new("weighted normals", "WEIGHTED_NORMAL")
    return ob

def sphere(name, loc, scale, mat):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=20, ring_count=12, location=loc)
    ob=bpy.context.object; ob.name=name
    ob.scale=scale
    ob.data.materials.append(mat)
    for poly in ob.data.polygons: poly.use_smooth=True
    return ob

def tapered(name, loc, radius_lower, radius_upper, depth, mat, bevel=.025):
    bpy.ops.mesh.primitive_cone_add(vertices=20, radius1=radius_lower, radius2=radius_upper, depth=depth, location=loc)
    ob=bpy.context.object;ob.name=name;ob.data.materials.append(mat)
    mod=ob.modifiers.new("soft clothing edge","BEVEL");mod.width=bevel;mod.segments=2
    ob.modifiers.new("weighted normals","WEIGHTED_NORMAL")
    return ob

def pose_segment(ob, a, b, frame):
    """Key one tapered arm section while keeping its endpoints attached."""
    va,vb=Vector(a),Vector(b);direction=vb-va
    ob.location=(va+vb)*.5
    ob.rotation_euler=direction.to_track_quat("Z","Y").to_euler()
    ob.scale.z=direction.length
    for prop in ("location","rotation_euler","scale"):
        ob.keyframe_insert(data_path=prop,frame=frame)

def grow_with_store(ob):
    if KIND!="P3": return
    ob.scale=(.01,.01,.01)
    ob.keyframe_insert(data_path="scale",frame=1)
    ob.keyframe_insert(data_path="scale",frame=42)
    ob.scale=(1,1,1)
    ob.keyframe_insert(data_path="scale",frame=83)

def curve_line(name, coords, radius, mat):
    curve=bpy.data.curves.new(name,"CURVE"); curve.dimensions="3D"; curve.resolution_u=12
    curve.bevel_depth=radius; curve.bevel_resolution=3
    spline=curve.splines.new("POLY"); spline.points.add(len(coords)-1)
    for p,co in zip(spline.points,coords): p.co=(*co,1)
    ob=bpy.data.objects.new(name,curve); bpy.context.collection.objects.link(ob)
    ob.data.materials.append(mat)
    return ob

def area(name, loc, energy, color, size, target):
    data=bpy.data.lights.new(name,"AREA"); data.energy=energy; data.color=color; data.shape="DISK"; data.size=size
    ob=bpy.data.objects.new(name,data); bpy.context.collection.objects.link(ob); ob.location=loc
    direction=Vector(target)-ob.location; ob.rotation_euler=direction.to_track_quat("-Z","Y").to_euler()
    return ob

def look(cam, target):
    direction=Vector(target)-cam.location
    cam.rotation_euler=direction.to_track_quat("-Z","Y").to_euler()

def cam_key(cam, frame, loc, target, lens=35):
    cam.location=loc; look(cam,target); cam.data.lens=lens
    cam.keyframe_insert(data_path="location",frame=frame)
    cam.keyframe_insert(data_path="rotation_euler",frame=frame)
    cam.data.keyframe_insert(data_path="lens",frame=frame)

# Floor and a sparse architectural kit.
box("floor", (0,0,-.095), (18,24,.17), FLOOR, .04)
for s in LAYOUT["shelves"]:
    x,y=s["x"],s["y"]; w,l,h=s["width"],s["length"],s["height"]
    body=box(s["id"]+" monolith", (x,y,h/2), (w,l,h), SHELF, .045)
    if KIND=="P3":
        body.scale.z=.012; body.keyframe_insert(data_path="scale",frame=1)
        body.scale.z=.012; body.keyframe_insert(data_path="scale",frame=42)
        body.scale.z=1; body.keyframe_insert(data_path="scale",frame=83)
    for level in (0.5,1.05,1.6,2.16):
        for side in (-1,1):
            strip=box(s["id"]+" shelf rail", (x+side*(w/2+.015),y,level),(.035,l-.18,.045),SHELF_FACE,.01)
            grow_with_store(strip)
        for yi in range(6):
            yy=y-l/2+.55+yi*(l-.9)/5
            for side in (-1,1):
                palette=(STOCK_A,STOCK_B,STOCK_C)
                height=(.20,.27,.24)[(yi+int(level*10))%3]
                width=(.17,.22,.19)[(yi+2*int(level*10))%3]
                item=box(s["id"]+" abstract stock", (x+side*(w/2+.045),yy,level+.12+height/2),
                         (.08,width,height),palette[(yi+int(level*10))%3],.012)
                grow_with_store(item)
    for end in (-1,1):
        cap=box(s["id"]+" end cap",(x,y+end*(l/2-.05),h/2),(.055,.08,h-.15),SHELF_FACE,.01)
        grow_with_store(cap)
# Cool floor joints, a few intentional ceiling light lines.
for x in (-5.25,-2.75,0,3,5.25):
    curve_line("quiet floor joint",[(x,-6,.008),(x,5.8,.008)],.005,SHELF_FACE)
if KIND!="P7":
    for x in (-3.0,3.0):
        box("ceiling light housing",(x,-.8,3.55),(.06,8,.025),SHELF_FACE,.01)
        box("ceiling cool strip",(x,-.8,3.52),(.025,7.8,.011),SOFT_MINT,.003)

def shopper(x,y,angle=0):
    parts=[]
    def child(ob):
        # The sculptural coat mesh has world-space vertices while primitives
        # have world-space object locations. Move both by the same delta.
        parts.append((ob,ob.location.copy()))
        return ob
    # One continuous lofted coat mass, not stacked mannequin primitives.
    rings=[(.77,.27,.18),(.86,.30,.19),(1.02,.29,.18),(1.20,.28,.18),
           (1.42,.35,.20),(1.55,.36,.19),(1.64,.17,.13)]
    n=32; verts=[]; faces=[]
    for z,rx,ry in rings:
        verts.extend((x+math.cos(2*math.pi*i/n)*rx,y+math.sin(2*math.pi*i/n)*ry,z) for i in range(n))
    for j in range(len(rings)-1):
        for i in range(n): faces.append((j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i))
    faces.extend([tuple(reversed(range(n))),tuple((len(rings)-1)*n+i for i in range(n))])
    mesh=bpy.data.meshes.new("sculpted coat mesh");mesh.from_pydata(verts,[],faces);mesh.update()
    coat=bpy.data.objects.new("continuous sculptural coat",mesh);bpy.context.collection.objects.link(coat)
    coat.data.materials.append(COAT)
    sculpt=coat.modifiers.new("soft sculptural silhouette","SUBSURF")
    sculpt.levels=1;sculpt.render_levels=1
    bevel=coat.modifiers.new("seamless coat bevel","BEVEL");bevel.width=.045;bevel.segments=2
    coat.modifiers.new("weighted coat normals","WEIGHTED_NORMAL")
    for poly in coat.data.polygons: poly.use_smooth=True
    child(coat)
    child(box("low contrast collar",(x,y,1.61),(.33,.25,.065),COAT_EDGE,.025))
    child(sphere("faceless sculptural head",(x,y,1.83),(.16,.15,.22),HEAD))
    child(curve_line("rear coat center seam",[(x,y+.19,.88),(x,y+.205,1.18),(x,y+.19,1.42)],.003,COAT_THREAD))
    for sign in (-1,1):
        sleeve=child(tapered("soft tapered sleeve",(x+sign*.34,y,1.26),.078,.105,.58,COAT))
        sleeve.scale.y=.82
        child(sphere("sculpted shoulder",(x+sign*.32,y,1.49),(.09,.135,.09),COAT))
        child(tapered("trouser",(x+sign*.17,y,0.45),.095,.13,.72,COAT_EDGE))
        child(box("shoe",(x+sign*.17,y-.08,.075),(.20,.34,.14),COAT,.035))
    return parts

def animate_shopper_path(parts, keypoints, last_frame, stride_frames=21):
    """Short readable steps without a full gait rig or repetitive walk cycle."""
    for frame in range(1,last_frame+1):
        for (f0,x0,y0),(f1,x1,y1) in zip(keypoints,keypoints[1:]):
            if frame<=f1:
                u=max(0,min(1,(frame-f0)/(f1-f0)))
                eased=u*u*(3-2*u)
                dx=x0+(x1-x0)*eased;dy=y0+(y1-y0)*eased
                direction=Vector((x1-x0,y1-y0,0))
                if direction.length: direction.normalize()
                break
        else:
            _,dx,dy=keypoints[-1]
            direction=Vector((0,1,0))
        phase=math.tau*frame/stride_frames
        for ob,base in parts:
            offset=Vector((dx,dy,0))
            name=ob.name
            if name.startswith(("trouser","shoe")):
                leg_phase=phase+(math.pi if name.endswith(".001") else 0)
                offset+=direction*(.065 if name.startswith("trouser") else .10)*math.sin(leg_phase)
                if name.startswith("shoe"):
                    offset.z+=.05*max(0,math.sin(leg_phase))
            else:
                offset.z+=.006*math.cos(2*phase)
            ob.location=base+offset
            ob.keyframe_insert(data_path="location",frame=frame)

# Shared route, visually grounded and walkable.
routepts=[(p["x"],p["y"],.035) for p in LAYOUT["route"]]
if KIND in ("P3","P4","P5","P6","P7"):
    path=curve_line("same path in world",routepts,.029,MINT)
    path.data.bevel_factor_end=0.0 if KIND=="P3" else (.92 if KIND=="P4" else 1)
    path.data.keyframe_insert(data_path="bevel_factor_end",frame=1)
    path.data.bevel_factor_end=1
    path.data.keyframe_insert(data_path="bevel_factor_end",frame=85 if KIND=="P3" else (60 if KIND=="P4" else FRAME_COUNT))

if KIND=="P1":
    person=shopper(-5.1,-5.2,math.radians(-8))
    ph=box("held phone",(-4.70,-5.39,1.14),(.20,.045,.38),SHELF_FACE,.035)
    ph.keyframe_insert(data_path="location",frame=70)
    ph.location.z=1.55; ph.location.x=-4.62; ph.keyframe_insert(data_path="location",frame=98)
    # Controlled light hierarchy; geometry stays fixed.
    key=area("shopper reveal key",(-5,-4,6),650,(.44,.72,.69),5,(-5,-5,1))
    key.data.energy=400;key.data.keyframe_insert(data_path="energy",frame=74)
    key.data.energy=1000;key.data.keyframe_insert(data_path="energy",frame=105)
    area("aisle streak",(2,-2,5),600,(.43,.72,.76),7,(0,0,0))
    camd=bpy.data.cameras.new("cinema camera"); cam=bpy.data.objects.new("cinema camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(0,-6.4,.65),(0,-1.7,1.3),29)
    cam_key(cam,34,(0,-2.1,.7),(0,2.4,1.4),29)
    cam_key(cam,58,(2.7,-1.8,1.05),(2.8,3.6,1.1),30)
    cam_key(cam,75,(-1.8,-7.2,7.0),(-4.55,-4.4,1.1),34)
    cam_key(cam,120,(-2.6,-7.5,6.5),(-4.85,-4.8,1.2),43)
elif KIND=="P3":
    # The top-down footprints rise continuously into store architecture as the camera descends.
    area("overhead key",(0,0,12),1150,(.46,.78,.72),12,(0,0,0))
    area("side mint",(6,1,5),600,(.31,.76,.61),8,(1,0,0))
    camd=bpy.data.cameras.new("map entry camera");cam=bpy.data.objects.new("map entry camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(0,-2,14),(0,-1,0),27)
    cam_key(cam,35,(0,-2,10),(0,-1,0),28)
    cam_key(cam,56,(0,-3,7),(0,-1,0),30)
    cam_key(cam,85,(0,-4.8,3.4),(0,1,1),31)
    cam_key(cam,120,(0,-3.8,1.35),(0,3,1.05),35)
    person=shopper(0,4.5,math.radians(15))
elif KIND=="P5":
    # Carry P3's forward direction into a low, accelerating route chase.
    person=shopper(0,4.5,0)
    animate_shopper_path(person,[(1,0,0),(75,2.1,.3)],75)
    area("low route rim",(0,2.5,4.0),650,(.25,.78,.66),6,(0,1,.3))
    camd=bpy.data.cameras.new("low route chase camera")
    cam=bpy.data.objects.new("low route chase camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(0,-3.8,1.35),(0,3,1.05),35)
    cam_key(cam,35,(0,-.1,.62),(0,4.3,.42),32)
    cam_key(cam,75,(0,2.2,.75),(2.65,4.8,.75),34)
elif KIND=="P6":
    # A lateral move reveals the same shopper as the route turns right.
    person=shopper(2.1,4.8,0)
    animate_shopper_path(person,[(1,0,0),(48,.9,0),(75,.9,-.75)],75)
    area("lateral shopper edge",(3.1,6.4,4.5),700,(.40,.79,.73),5,(3,4.5,1))
    camd=bpy.data.cameras.new("lateral reveal camera")
    cam=bpy.data.objects.new("lateral reveal camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(-1.4,9.5,1.8),(2.1,4.8,1.2),36)
    cam_key(cam,38,(1.25,9.6,1.6),(2.75,4.65,1.05),36)
    cam_key(cam,75,(4.3,9.5,1.65),(3.0,3.95,1.05),35)
elif KIND=="P7":
    # Show the remaining turn from above, then drop behind the destination aisle.
    person=shopper(3.0,4.05,math.radians(180))
    animate_shopper_path(person,[(1,0,0),(47,0,-8.9),(63,2.05,-8.9),(90,2.3,-2.95)],90,13)
    area("overhead navigation key",(3,-1,9),1100,(.42,.79,.72),11,(3,0,0))
    camd=bpy.data.cameras.new("overhead to turn camera")
    cam=bpy.data.objects.new("overhead to turn camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(2.2,5.2,8.3),(3.0,1.1,.4),31)
    cam_key(cam,45,(3.5,-2.8,7.5),(4.0,-4.1,.4),34)
    cam_key(cam,90,(5.0,-5.6,1.28),(5.05,1.9,.8),34)
else:
    person=shopper(5.3,2.1,math.radians(90))
    # Warm generic milk carton mounted on target shelf face.
    box("milk carton",(4.52,2.7,1.38),(.20,.34,.49),MILK,.018)
    roof_verts=[(4.42,2.53,1.625),(4.62,2.53,1.625),(4.62,2.87,1.625),(4.42,2.87,1.625),
                (4.52,2.53,1.79),(4.52,2.87,1.79)]
    roof_faces=[(0,1,4),(3,5,2),(0,4,5,3),(1,2,5,4),(0,3,2,1)]
    roof_mesh=bpy.data.meshes.new("folded carton roof mesh")
    roof_mesh.from_pydata(roof_verts,[],roof_faces);roof_mesh.update()
    roof=bpy.data.objects.new("folded milk carton roof",roof_mesh)
    bpy.context.collection.objects.link(roof);roof.data.materials.append(MILK_TOP)
    box("milk mint label",(4.635,2.7,1.36),(.007,.24,.17),SOFT_MINT,.002)
    box("milk paper face line",(4.641,2.7,1.52),(.005,.22,.012),COAT_THREAD,.002)
    print_data=bpy.data.curves.new("generic milk label type","FONT")
    print_data.body="MILCH";print_data.size=.046;print_data.align_x="CENTER"
    print_data.extrude=.0005
    print_ob=bpy.data.objects.new("printed milk name",print_data)
    bpy.context.collection.objects.link(print_ob)
    print_ob.location=(4.645,2.75,1.345)
    print_ob.rotation_euler=(math.pi/2,0,math.pi/2)
    print_ob.data.materials.append(INK)
    # Two tapered sleeve sections and a small hand keep the reach attached
    # at shoulder, elbow and wrist without a fragile full-body rig.
    upper=tapered("reaching upper sleeve",(5.1,2.1,1.2),.09,.12,1,COAT,.018)
    lower=tapered("reaching forearm sleeve",(5.1,2.1,1.1),.073,.09,1,COAT,.015)
    hand=sphere("restrained hand",(5.1,2.05,1.07),(.077,.082,.065),HEAD)
    shoulder=(5.05,2.1,1.47)
    poses=[(74,(5.08,2.08,1.19),(5.08,2.08,1.09)),
           (114,(4.95,2.31,1.20),(4.65,2.63,1.48))]
    for f,elbow,wrist in poses:
        pose_segment(upper,shoulder,elbow,f)
        pose_segment(lower,elbow,wrist,f)
        hand.location=wrist;hand.keyframe_insert(data_path="location",frame=f)
    area("destination milk key",(4.9,2.5,4.6),550,(.72,.96,.83),3,(4.3,2.7,1.2))
    area("shopper rim",(6,0,3),300,(.30,.70,.64),4,(5,2,1))
    camd=bpy.data.cameras.new("arrival camera");cam=bpy.data.objects.new("arrival camera",camd);bpy.context.collection.objects.link(cam);scene.camera=cam
    cam_key(cam,1,(5.0,-5.6,.64),(5.0,-1.0,.48),32)
    cam_key(cam,45,(5.08,-1.6,.85),(5.0,2.3,.8),34)
    cam_key(cam,80,(7.8,4.3,3.1),(4.55,2.7,.7),32)
    cam_key(cam,120,(7.55,4.0,2.9),(4.55,2.7,.72),35)

# A deep background, restrained ambient light and contact shadows.
world=bpy.data.worlds.new("dark ambient")
scene.world=world;world.use_nodes=True
world.node_tree.nodes["Background"].inputs["Color"].default_value=(.018,.036,.044,1)
world.node_tree.nodes["Background"].inputs["Strength"].default_value=.38
area("broad ceiling",(0,0,9),900,(.65,.83,.88),12,(0,0,0))
scene.camera.data.clip_end=200
scene.render.engine="BLENDER_EEVEE"
scene.render.filepath=str(outdir/"frame_")
tracked={
    "P1":{"shopper":(-5.1,-5.2,1.4),"phone":(-4.62,-5.39,1.55)},
    "P3":{"routeStart":(-5.1,-5.2,.04),"routeCenter":(0,-1,.04)},
    "P4":{"destination":(5.05,2.7,.04),"milk":(4.52,2.7,1.38)}
}.get(KIND,{})
projection=[]
for f in range(1,FRAME_COUNT+1):
    scene.frame_set(f)
    projection.append({name:dict(x=round((q:=world_to_camera_view(scene,scene.camera,Vector(point))).x*1280,2),
                                 y=round((1-q.y)*720,2),visible=q.z>0)
                       for name,point in tracked.items()})
if tracked:
    (ROOT/"src/data"/f"projection-{KIND}.json").write_text(json.dumps(projection,separators=(",",":")))
if STILL is None:
    bpy.ops.render.render(animation=True)
else:
    if not 1<=STILL<=FRAME_COUNT: raise ValueError(f"still_frame must be 1..{FRAME_COUNT}")
    scene.frame_set(STILL)
    scene.render.filepath=str(outdir/f"still_{STILL:04d}.png")
    bpy.ops.render.render(write_still=True)
